/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.io.File;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void testingQuotesConstructor(){
        // Arrange
        // Act
        Quotes testQuotes = new Quotes("Charles Dickens", "Ask no questions, and you'll be told no lies.");
        // Assert
        assertEquals("Ask no questions, and you'll be told no lies.", testQuotes.getText());
        assertEquals("Charles Dickens", testQuotes.getAuthor());

    }
}
